blank_issues_enabled: true
contact_links:
  - name: Otra solicitud
    url: https://ministeriodesalud.go.cr/index.php/contactenos/consultas-telefonicas-o-email
    about: Para solicitar algo que no sea un informe de error
